# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  SvenLie\WordpressMigrate\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Nitsan\NsNewsComments\Domain\Repository\CommentRepository:
    public: true